### ISSUE TITLE
I've had it with these... names in this... DataFrame

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#74]
Okay, sorry, I couldn't help myself.

Anyway, onto the problem. `?DataFrame` states the following:

>  Constructs a ‘DataFrame’ in similar fashion to ‘data.frame’.
Each argument in ‘...’ is coerced to a ‘DataFrame’ and
combined column-wise. No special effort is expended to
automatically determine the row names from the arguments. The
row names should be given in ‘row.names’; otherwise, there
are no row names. This is by design, as row names are
normally undesirable when data is large. If ‘check.names’ is
‘TRUE’, the column names will be checked for syntactic
validity and made unique, if necessary.

Unfortunately, this does not seem to be the case:

```r
library(S4Vectors)
df <- DataFrame(X=c(A=1, B=2))
df
## DataFrame with 2 rows and 1 column
##           X
##   <numeric>
## A         1
## B         2
```

You can see that I'm getting row names without ever specifying `row.names=`, contrary to the documentation.

If the documentation is not correct, and the above behavior is intended, then it would be nice to have an argument to `DataFrame()` that turns off any name inheritance "for good". This is necessary to guarantee that I do not get any names in my `DataFrame` unless I explicitly ask for it. One can see how inadvertent names can cause problems when the DF's are used in the SE constructor; the non-`NULL` names for the `colData=` override the matrix's column names, leading to unexpected names for the SE.

<details>
<summary>Session information</summary>

```
R Under development (unstable) (2020-10-31 r79390)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /home/luna/Software/R/trunk/lib/libRblas.so
LAPACK: /home/luna/Software/R/trunk/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] S4Vectors_0.29.3    BiocGenerics_0.37.0

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0   
```
</details>

**Comment by lawremi** [comment]
The documentation was out of date, as we have moved towards more compatibility with data.frame over the years. Just like data.frame, you can pass `row.names=NULL` to avoid inference of the rownames from the arguments. There was also a bug in the `show()` method that made it look like there were rownames even when they were disabled by `row.names=NULL`. Both the documentation and the rendering are now fixed.

**Comment by LTLA** [comment]
Couldn't you make the `row.names` argument missing in the constructor, then? If you tell me that `row.names=NULL` is necessary to turn off row names, it's confusing to look at `?DataFrame` and see that `row.names=NULL` already but I'm still getting row names. Having `row.names` without a default would serve the same purpose if you're going to override it anyway.

**Comment by lawremi** [comment]
It's just for consistency with `data.frame()`.

**Comment by LTLA** [comment]
`DataFrame()`'s default arguments are already a little inconsistent due to `stringsAsFactors` so there might not be any harm in having `row.names` also be a missing argument. Either that, or you'll need a few more lines in the documentation explaining why the default `row.names=NULL` does not really mean `row.names=NULL` (as is explained in `?data.frame`, for example).

**Comment by lawremi** [comment]
Agreed, and I guess I read your mind, because I just added that documentation.

**Comment by hpages** [comment]
@lawremi Hi Michael,

It's been brought to my attention that a few packages (including S4Vectors) started to fail recently on all platforms with a "duplicate row.names: xxx" error:

- https://bioconductor.org/checkResults/3.13/bioc-LATEST/S4Vectors/malbec2-checksrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/GenomicRanges/malbec2-buildsrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/SummarizedExperiment/malbec2-checksrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/ensembldb/malbec2-buildsrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/diffcyt/malbec2-buildsrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/spicyR/malbec2-buildsrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/SplicingGraphs/malbec2-buildsrc.html
- https://bioconductor.org/checkResults/3.13/bioc-LATEST/TSCAN/malbec2-checksrc.html

I suspect this has to do with commit 735c6b7 where:
```
df <- as.data.frame(lapply(x, showAsCell), optional=TRUE)
```
got replaced with:
```
df <- data.frame(lapply(x, showAsCell), check.names=FALSE, row.names=rownames(x))
```
in the `makeNakedCharacterMatrixForDisplay()` method for DataFrame derivatives. Unfortunately the new code breaks when the DataFrame has duplicate row names.

Thanks!

P.S.: BTW it takes less than 3 min. to run `R CMD build` + `R CMD check` on **S4Vectors** so not a big deal. It was painful to do this in the pre-**S4Vectors** era when all the DataFrame stuff was in **IRanges** but not anymore ;-)

**Comment by hpages** [comment]
Any chance you can take a look at this @lawremi ? Thx

**Comment by lawremi** [comment]
This should be fixed. Sorry for missing the initial ping.

**Comment by hpages** [comment]
Thanks Michael!
